name: AI Code Review Working

on:
  push:
    branches: [master]
  pull_request:
    types: [opened]

jobs:
  ai-review:
    runs-on: ubuntu-latest
    name: AI Code Review

    steps:
    - uses: actions/checkout@v4

    - name: Test Variables
      run: |
        echo "Current directory: $(pwd)"
        echo "Python files:"
        find . -name "*.py" | head -5

    - name: AI Review
      env:
        API_KEY: ${{ secrets.UPSTREAM_API_KEY }}
      run: |
        echo "Starting AI review..."

        # Get Python files
        FILES=$(find . -name "*.py" | tr '\n' ' ')
        echo "Found files: $FILES"

        if [ -n "$FILES" ]; then
          echo "Making API call..."

          # Create JSON request properly
          JSON_DATA=$(cat <<EOF
        {
          "model": "glm-4.6",
          "max_tokens": 300,
          "messages": [
            {
              "role": "user",
              "content": "Review these files: $FILES"
            }
          ]
        }
        EOF
        )

          echo "Request data: $JSON_DATA"

          HTTP_STATUS=$(curl -s \
            -w "%{http_code}" \
            -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $API_KEY" \
            -d "$JSON_DATA" \
            "https://apis.iflow.cn/v1/chat/completions" \
            -o response.json)

          echo "HTTP Status: $HTTP_STATUS"

          if [ "$HTTP_STATUS" = "200" ]; then
            echo "API call successful"
            if command -v jq >/dev/null 2>&1; then
              CONTENT=$(jq -r '.choices[0].message.content // "No content"' response.json)
            else
              CONTENT=$(cat response.json | grep -o '"content":"[^"]*"' | cut -d'"' -f4 || "Parse error")
            fi
            echo "AI Response: $CONTENT"
          else
            echo "API call failed"
            cat response.json
          fi
        else
          echo "No Python files found"
        fi