name: AI Code Review

on:
  push:
    branches: [main, master]
  pull_request:
    types: [opened]

jobs:
  review:
    runs-on: ubuntu-latest
    name: Code Review

    steps:
      - uses: actions/checkout@v4

      - name: AI Review
        env:
          API_KEY: ${{ secrets.UPSTREAM_API_KEY }}
        run: |
          echo "Starting AI review..."

          # Check if we have code files
          FILES=$(find . -name "*.py" -o -name "*.js" -o -name "*.ts" 2>/dev/null)

          if [ -n "$FILES" ]; then
            echo "Found files: $FILES"

            response=$(curl -s \
              -H "Content-Type: application/json" \
              -H "Authorization: Bearer $API_KEY" \
              -d '{
                "model": "glm-4.6",
                "max_tokens": 300,
                "messages": [{"role": "user", "content": "Review these files: '$FILES'"}]
              }' \
              "https://apis.iflow.cn/v1/chat/completions")

            echo "Response: $response"

            if echo "$response" | grep -q '"content"'; then
              content=$(echo "$response" | grep -o '"content":"[^"]*"' | cut -d'"' -f4)
              echo "AI Analysis: $content"
            else
              echo "No content in response"
            fi
          else
            echo "No code files found"
          fi