name: Claude Code App Integration

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [main, master]

jobs:
  claude-code-review:
    runs-on: ubuntu-latest
    name: Claude Code Analysis

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Claude Code GitHub App
      uses: anthropics/claude-code-action@v1
      with:
        api-key: ${{ secrets.ANTHROPIC_API_KEY }}
        base-url: https://blue-spoons-run.loca.lt
        model: glm-4.6
        max-tokens: 4000

    - name: Analyze Code Changes
      run: |
        echo "Claude Code will analyze recent changes..."
        git diff --name-only HEAD~1 HEAD

    - name: Generate Code Review
      run: |
        curl -X POST "https://blue-spoons-run.loca.lt/v1/messages" \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ secrets.ANTHROPIC_API_KEY }}" \
          -d '{
            "model": "glm-4.6",
            "max_tokens": 1000,
            "messages": [
              {
                "role": "user",
                "content": "请分析以下代码变更，提供改进建议：\n\n'"$(git diff --name-only HEAD~1 HEAD | head -5 | tr '\n' ' ')"'"
              }
            ]
          }'

  test-github-app:
    runs-on: ubuntu-latest
    name: Test GitHub App Connection
    steps:
    - name: Test API Connection
      run: |
        echo "Testing connection to local converter..."
        curl -X GET "https://blue-spoons-run.loca.lt/health" \
          -H "User-Agent: GitHub-Actions/1.0"

        echo "Testing model list..."
        curl -X GET "https://blue-spoons-run.loca.lt/v1/models" \
          -H "User-Agent: GitHub-Actions/1.0"