name: Simple Test

on:
  push:
    branches: [master]

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test Simple Command
        run: echo "Hello World"

      - name: Test Variables
        env:
          TEST_VAR: "test value"
        run: |
          echo "Variable is: $TEST_VAR"
          echo "Current directory: $(pwd)"
          ls -la